import { artifactsDir, captureScreenshot, expect, expectNoDocumentVerticalOverflow, expectNoHorizontalOverflow, test } from './helpers'

test('mock registration, voice reconnect, committed history and result survive reload', async ({ page }) => {
  test.skip(process.env.VITE_AUTH_SOURCE !== 'mock' || process.env.VITE_NEGOTIATION_SOURCE !== 'mock' || process.env.VITE_AUDIO_SOURCE !== 'mock', 'Requires full mock mode.')
  test.setTimeout(70_000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/register')
  await page.getByLabel('Имя', { exact: true }).fill('Ирина')
  await page.getByLabel('Фамилия').fill('Петрова')
  await page.getByLabel('Email').fill('voice@example.com')
  await page.getByLabel('Пароль').fill('strong-password')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByRole('link', { name: 'Открыть demo-ссылку активации' }).click()
  await expect(page.getByRole('heading', { name: 'Аккаунт активирован' })).toBeVisible()
  await page.getByRole('link', { name: 'Перейти в приложение' }).click()
  await expect(page).toHaveURL(/\/home$/)

  await page.getByRole('button', { name: 'Начать кейс' }).click()
  const modal = page.getByRole('dialog', { name: 'Повышение зарплаты' })
  await modal.getByRole('radio', { name: /Сотрудник/ }).check()
  await modal.getByText('Голос', { exact: true }).click()
  await modal.getByRole('button', { name: 'Начать подготовку' }).click()
  await expect(page).toHaveURL(/\/cases\/salary-review\/preparation/)
  await page.locator('.preparation-sidebar').getByRole('button', { name: /Стратегия/ }).click()
  await page.getByRole('textbox', { name: 'BATNA', exact: true }).fill('Зафиксировать результаты и рассмотреть другие предложения.')
  await page.getByRole('button', { name: 'Начать поединок' }).first().click()
  await expect(page).toHaveURL(/\/arena\/[0-9a-f-]+$/)
  const arenaUrl = page.url()
  await expect(page.getByRole('button', { name: 'Начать разговор' })).toBeVisible()
  await page.getByRole('button', { name: 'Меню профиля' }).click()
  await expect(page.getByRole('banner').getByRole('link', { name: 'К кейсам' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Пройти тур' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('heading', { name: 'Моя подготовка' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Повышение зарплаты' })).toBeVisible()
  await captureScreenshot(page, `${artifactsDir}/arena-voice-idle-desktop.png`)
  await page.getByRole('button', { name: /Открыть полностью/ }).click()
  await expect(page.getByText('BATNA')).toBeVisible()
  await page.getByRole('button', { name: /Свернуть/ }).click()
  await page.getByRole('button', { name: 'Начать разговор' }).click()
  await expect(page.locator('.arena-message--user.arena-message--partial')).toBeVisible()
  await expect(page.locator('.voice-controls__partial')).toHaveCount(0)
  await captureScreenshot(page, `${artifactsDir}/arena-voice-partial-desktop.png`)
  const beforeCommit = await page.evaluate(() => {
    const data = JSON.parse(window.localStorage.getItem('arena.mock.data.v1') ?? '{}') as { sessions?: Array<{ messages: unknown[] }> }
    return data.sessions?.[0]?.messages.length ?? 0
  })
  expect(beforeCommit).toBe(0)
  await expect(page.locator('.arena-message--ai.arena-message--partial')).toBeVisible()
  await expect(page.locator('.arena-message--partial')).toHaveCount(0)
  await expect(page.locator('.arena-message')).toHaveCount(2)
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/arena-voice-committed-desktop.png`)

  await page.getByRole('button', { name: 'Остановить' }).click()
  await page.getByRole('button', { name: 'Подключиться снова' }).click()
  await expect(page.locator('.arena-message:not(.arena-message--partial)')).toHaveCount(4, { timeout: 10_000 })
  await expect(page.locator('.arena-message--partial')).toHaveCount(0)
  const persisted = await page.evaluate(() => {
    const data = JSON.parse(window.localStorage.getItem('arena.mock.data.v1') ?? '{}') as { sessions?: Array<{ messages: Array<{ id: string; sequence: number }> }>; audioTickets?: Array<{ ticket: string }> }
    return { messages: data.sessions?.[0]?.messages ?? [], tickets: data.audioTickets?.length ?? 0 }
  })
  expect(new Set(persisted.messages.map((message) => message.id)).size).toBe(4)
  expect(persisted.messages.map((message) => message.sequence)).toEqual([1, 2, 3, 4])
  expect(persisted.tickets).toBe(2)

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  const preparation = page.locator('.duel-preparation')
  await expect(preparation.getByRole('button', { name: /Моя подготовка/ })).toHaveAttribute('aria-expanded', 'false')
  await preparation.getByRole('button', { name: /Моя подготовка/ }).click()
  await expect(preparation.getByText('BATNA')).toBeVisible()
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/arena-voice-preparation-mobile.png`)
  await preparation.getByRole('button', { name: /Моя подготовка/ }).click()
  await captureScreenshot(page, `${artifactsDir}/arena-voice-mobile.png`)
  await expectNoDocumentVerticalOverflow(page)
  await page.setViewportSize({ width: 360, height: 800 })
  await expectNoHorizontalOverflow(page)
  await expectNoDocumentVerticalOverflow(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.locator('.arena-message')).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Начать разговор' })).toBeVisible()
  await page.getByRole('button', { name: 'Завершить' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Завершить' }).click()
  await expect(page).toHaveURL(/\/result\/[0-9a-f-]+$/)
  await expect(page.getByRole('heading', { name: 'Разбор поединка' })).toBeVisible()
  await page.getByRole('button', { name: 'Меню профиля' }).click()
  await expect(page.getByRole('banner').getByRole('link', { name: 'К кейсам' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Пройти тур' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/result-voice-mobile.png`)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Разбор поединка' })).toBeVisible()
  await page.getByRole('link', { name: 'К кейсам' }).first().click()
  await expect(page.getByRole('heading', { name: 'Последние тренировки' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Открыть тренировку «Повышение зарплаты»' })).toBeVisible()
  await page.getByRole('heading', { name: 'Последние тренировки' }).scrollIntoViewIfNeeded()
  await captureScreenshot(page, `${artifactsDir}/home-history-mobile.png`)
  await page.getByRole('link', { name: 'Открыть тренировку «Повышение зарплаты»' }).click()
  await expect(page.getByRole('heading', { name: 'Разбор поединка' })).toBeVisible()
  await page.goto(arenaUrl)
  await expect(page).toHaveURL(/\/result\/[0-9a-f-]+$/)
})
