import { artifactsDir, captureScreenshot, dismissProductTourInvitation, expect, expectNoHorizontalOverflow, test } from './helpers'

async function enterHome(page: import('@playwright/test').Page) {
  await page.goto('/register')
  await page.getByLabel('Имя', { exact: true }).fill('Кирилл')
  await page.getByLabel('Фамилия').fill('Тестовый')
  await page.getByLabel('Email').fill('home.visual@example.com')
  await page.getByLabel('Пароль').fill('strong-password')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByRole('link', { name: 'Открыть demo-ссылку активации' }).click()
  await page.getByRole('link', { name: 'Перейти в приложение' }).click()
  await expect(page).toHaveURL(/\/home$/)
  const continueCard = page.locator('.arena-home__continue')
  const progressCard = page.locator('.arena-home__progress')
  await expect(continueCard.getByRole('status', { name: 'Загружаем тренировку' })).toBeVisible()
  await expect(continueCard.getByText('Повышение зарплаты')).toHaveCount(0)
  await expect(progressCard).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Кейсы' })).toBeVisible()
  await expect(continueCard.getByRole('status', { name: 'Загружаем тренировку' })).toHaveCount(0)
  await dismissProductTourInvitation(page)
}

test('home dashboard and case dialog fit desktop and mobile', async ({ page }) => {
  test.setTimeout(30_000)
  test.skip(process.env.VITE_AUTH_SOURCE !== 'mock', 'Requires mock auth.')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await enterHome(page)
  await expect(page.getByText('Здесь появятся ваши тренировки.')).toBeVisible()
  await expect(page.locator('.arena-home__progress')).toContainText('0тренировок')
  await expect(page.locator('.home-case-card')).toHaveCount(6)
  await expect(page.locator('.home-case-card img')).toHaveCount(0)
  await expect(page.locator('.home-case-card__roles')).toHaveCount(0)
  await expect(page.locator('.home-case-card__role-arrow')).toHaveCount(0)
  await expect(page.locator('.home-case-card__arrow')).toHaveCount(0)
  await expect(page.locator('.home-case-card').first()).not.toContainText('Сотрудник')
  await expect(page.locator('.home-case-card').first()).not.toContainText('Руководитель')
  const profileTrigger = page.getByRole('button', { name: 'Меню профиля' })
  await profileTrigger.click()
  await expect(page.getByRole('link', { name: 'К кейсам' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Пройти тур' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Настроить 2FA' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Выйти' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(profileTrigger).toBeFocused()
  await profileTrigger.click()
  await page.getByRole('button', { name: 'Настроить 2FA' }).click()
  const securityDialog = page.getByRole('dialog', { name: 'Двухфакторная защита' })
  await expect(securityDialog.getByRole('button', { name: 'Закрыть' })).toBeFocused()
  await expect(page.locator('#root')).toHaveJSProperty('inert', true)
  await page.keyboard.press('Escape')
  await expect(securityDialog).toHaveCount(0)
  await expect(profileTrigger).toBeFocused()
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: `${artifactsDir}/home-dashboard-desktop.png`, animations: 'disabled', fullPage: true })

  const employeeCaseTrigger = page.getByRole('button', { name: 'Выбрать кейс «Сложный сотрудник»' })
  await employeeCaseTrigger.click()
  const dialog = page.getByRole('dialog', { name: 'Сложный сотрудник' })
  await expect(dialog.getByRole('button', { name: 'Закрыть' })).toBeFocused()
  await expect(page.locator('.arena-home > main')).toHaveJSProperty('inert', true)
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('radio', { name: 'Голос' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Закрыть' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(employeeCaseTrigger).toBeFocused()
  await employeeCaseTrigger.click()
  await expect(dialog.getByRole('radio', { name: /Руководитель/ })).not.toBeChecked()
  await expect(dialog.getByRole('radio', { name: /Сотрудник/ })).not.toBeChecked()
  await expect(dialog.getByText('Ваша роль')).toHaveCount(0)
  await expect(dialog.getByText('AI-оппонент', { exact: true })).toHaveCount(0)
  await expect(dialog.locator('.home-case-modal__role.is-selected, .home-case-modal__role.is-opponent')).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'Начать подготовку' })).toBeDisabled()
  await dialog.getByRole('radio', { name: /Сотрудник/ }).check()
  await expect(dialog.getByRole('radio', { name: /Сотрудник/ })).toBeChecked()
  await expect(dialog.getByText('Ваша роль')).toBeVisible()
  await expect(dialog.getByText('AI-оппонент', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Начать подготовку' })).toBeEnabled()
  await expect(dialog.getByText('Текст', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Голос', { exact: true })).toBeVisible()
  await captureScreenshot(page, `${artifactsDir}/home-case-dialog-desktop.png`)
  await dialog.getByRole('button', { name: 'Закрыть' }).click()
  await expect(employeeCaseTrigger).toBeFocused()

  await page.setViewportSize({ width: 390, height: 844 })
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: `${artifactsDir}/home-dashboard-mobile.png`, animations: 'disabled', fullPage: true })
  await page.getByRole('button', { name: 'Выбрать кейс «Сложный сотрудник»' }).click()
  await expect(dialog).toBeVisible()
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/home-case-dialog-mobile.png`)
  const dragHandle = dialog.locator('.home-case-modal__drag-handle')
  await dragHandle.dispatchEvent('pointerdown', { pointerId: 1, pointerType: 'touch', isPrimary: true, clientX: 195, clientY: 12 })
  await dragHandle.dispatchEvent('pointermove', { pointerId: 1, pointerType: 'touch', isPrimary: true, clientX: 198, clientY: 62 })
  await dragHandle.dispatchEvent('pointerup', { pointerId: 1, pointerType: 'touch', isPrimary: true, clientX: 198, clientY: 62 })
  await expect(dialog).toBeVisible()
  await expect(dialog).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
  await dragHandle.dispatchEvent('pointerdown', { pointerId: 2, pointerType: 'touch', isPrimary: true, clientX: 195, clientY: 12 })
  await dragHandle.dispatchEvent('pointermove', { pointerId: 2, pointerType: 'touch', isPrimary: true, clientX: 198, clientY: 132 })
  await dragHandle.dispatchEvent('pointerup', { pointerId: 2, pointerType: 'touch', isPrimary: true, clientX: 198, clientY: 132 })
  await expect(dialog).toHaveCount(0)
  await expect(employeeCaseTrigger).toBeFocused()
  await expect(page.locator('.home-case-card')).toHaveCount(6)
  await expectNoHorizontalOverflow(page)

  await page.getByRole('button', { name: 'Выбрать кейс «Повышение зарплаты»' }).click()
  const startDialog = page.getByRole('dialog', { name: 'Повышение зарплаты' })
  await startDialog.getByRole('radio', { name: /Сотрудник/ }).check()
  await startDialog.getByRole('button', { name: 'Начать подготовку' }).click()
  await expect(page).toHaveURL(/\/cases\/salary-review\/preparation/)
  await page.getByRole('button', { name: 'Начать поединок' }).first().click()
  await expect(page).toHaveURL(/\/arena\/[0-9a-f-]+$/)
  await page.goto('/home')
  await expect(page.locator('.arena-home__progress')).toContainText('1тренировка')
})
