import { artifactsDir, captureScreenshot, expect, expectNoHorizontalOverflow, test, type Page } from './helpers'

async function tourState(page: Page) {
  return page.evaluate(() => {
    const key = Object.keys(window.localStorage).find((candidate) => candidate.startsWith('arena.product-tour.v1.'))
    return key ? JSON.parse(window.localStorage.getItem(key) ?? 'null') as { stepId?: string; status?: string; caseId?: string; roleIndex?: number; sessionId?: string } | null : null
  })
}

test('product events advance the voice tour and expose stable targets', async ({ page }) => {
  test.skip(process.env.VITE_AUTH_SOURCE !== 'mock' || process.env.VITE_NEGOTIATION_SOURCE !== 'mock' || process.env.VITE_AUDIO_SOURCE !== 'mock', 'Requires full mock mode.')
  test.setTimeout(70_000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/register')
  await page.getByLabel('Имя', { exact: true }).fill('Тур')
  await page.getByLabel('Фамилия').fill('События')
  await page.getByLabel('Email').fill('tour.events@example.com')
  await page.getByLabel('Пароль').fill('strong-password')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByRole('link', { name: 'Открыть demo-ссылку активации' }).click()
  await page.getByRole('link', { name: 'Перейти в приложение' }).click()

  await page.getByRole('dialog', { name: 'Познакомимся с Ареной?' }).getByRole('button', { name: 'Начать тур' }).click()
  const caseTarget = page.locator('[data-tour-id="case-card"]')
  const tourCard = page.locator('[data-product-tour-tooltip]')
  await expect(caseTarget).toHaveCount(1)
  await expect(tourCard.getByRole('heading', { name: 'Начни с кейса' })).toBeVisible()
  await expect(tourCard.getByRole('status', { name: 'Шаг 1 из 12' })).toHaveText('1 из 12')
  await expect(tourCard.getByRole('list', { name: 'Шаги тура' })).toHaveCount(0)
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/product-tour-case-desktop.png`)
  await page.setViewportSize({ width: 390, height: 844 })
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/product-tour-case-mobile.png`)
  await page.setViewportSize({ width: 1440, height: 900 })

  await tourCard.getByRole('button', { name: 'Свернуть подсказку' }).click()
  const restoreTooltip = page.getByRole('button', { name: 'Показать подсказку' })
  await expect(tourCard).toHaveCount(0)
  await expect(restoreTooltip).toBeVisible()
  await expect(restoreTooltip).toBeFocused()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'case', status: 'active' })
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/product-tour-collapsed-desktop.png`)
  await page.setViewportSize({ width: 320, height: 700 })
  await restoreTooltip.scrollIntoViewIfNeeded()
  await expect(restoreTooltip).toBeVisible()
  await expectNoHorizontalOverflow(page)
  await captureScreenshot(page, `${artifactsDir}/product-tour-collapsed-mobile.png`)
  await page.setViewportSize({ width: 1440, height: 900 })
  await restoreTooltip.press('Enter')
  await expect(tourCard.getByRole('heading', { name: 'Начни с кейса' })).toBeVisible()
  await expect(tourCard.getByRole('button', { name: 'Свернуть подсказку' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(tourCard).toHaveCount(0)
  await expect(restoreTooltip).toBeFocused()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'case', status: 'active' })

  await caseTarget.click()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'role', caseId: 'salary-review' })

  const caseDialog = page.getByRole('dialog', { name: 'Повышение зарплаты' })
  await expect(caseDialog.locator('[data-tour-id="role-selector"]')).toBeVisible()
  await expect(tourCard).toHaveCount(0)
  await expect(restoreTooltip).toBeVisible()
  await restoreTooltip.press('Enter')
  await expect(tourCard.getByRole('heading', { name: 'Выбери свою роль' })).toBeVisible()
  await expect(tourCard.getByRole('button', { name: 'Свернуть подсказку' })).toBeFocused()
  await caseDialog.getByRole('radio', { name: /Сотрудник/ }).check()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'voice-format', roleIndex: 0 })
  await expect(caseDialog.getByRole('radio', { name: 'Текст' })).toHaveCount(0)
  await expect(caseDialog.getByRole('radio', { name: 'Голос' })).toBeChecked()
  await expect(tourCard.getByRole('heading', { name: 'Подготовься к голосовому разговору' })).toBeVisible()
  await caseDialog.getByRole('button', { name: 'Начать подготовку' }).click()

  await expect(page).toHaveURL(/mode=voice&section=analysis$/)
  await expect(page.locator('[data-tour-id="preparation-analysis"]')).toBeVisible()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'analysis' })
  await expect(tourCard.getByRole('heading', { name: 'Разбери ситуацию' })).toBeVisible()
  await tourCard.getByRole('button', { name: 'Далее' }).click()
  await expect(page.locator('[data-tour-id="preparation-strategy"]')).toBeVisible()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'strategy' })
  await expect(tourCard.getByRole('heading', { name: 'Собери стратегию' })).toBeVisible()
  await tourCard.getByRole('button', { name: 'Далее' }).click()
  await expect(page.locator('[data-tour-id="preparation-tactics"]')).toBeVisible()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'tactics' })
  await expect(tourCard.getByRole('heading', { name: 'Продумай тактику' })).toBeVisible()
  await tourCard.getByRole('button', { name: 'Далее' }).click()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'start-duel' })
  await expect(tourCard.getByRole('heading', { name: 'Выходи на поединок' })).toBeVisible()
  await page.locator('[data-tour-id="start-duel"]').click()

  await expect(page).toHaveURL(/\/arena\/[0-9a-f-]+$/)
  await expect(page.locator('[data-tour-id="microphone"]')).toBeVisible()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'microphone' })
  await expect(tourCard.getByRole('heading', { name: 'Включи микрофон' })).toBeVisible()
  await page.locator('[data-tour-id="microphone"]').click()
  await expect(page.locator('[data-tour-id="dialogue"] .arena-message')).toHaveCount(2, { timeout: 12_000 })
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'finish' })
  await expect(tourCard.getByRole('heading', { name: 'Ты управляешь длительностью' })).toBeVisible()

  const finishTarget = page.locator('[data-tour-id="finish"]')
  await finishTarget.click()
  const finishDialog = page.locator('[data-tour-id="finish-dialog"]')
  await expect(finishDialog).toBeVisible()
  await expect(finishDialog.getByRole('button', { name: 'Продолжить диалог' })).toBeFocused()
  await expect(page.locator('.arena-page > main')).toHaveJSProperty('inert', true)
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'confirm-finish' })
  await expect(tourCard.getByRole('heading', { name: 'Подтверди завершение' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(finishDialog).toHaveCount(0)
  await expect(finishTarget).toBeFocused()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'finish' })

  await finishTarget.click()
  await finishDialog.getByRole('button', { name: 'Завершить' }).click()
  await expect(page).toHaveURL(/\/result\/[0-9a-f-]+$/)
  await expect(page.locator('[data-tour-id="result"]')).toBeVisible({ timeout: 15_000 })
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'result', status: 'active' })
  await expect(tourCard.getByRole('heading', { name: 'Разбор готов' })).toBeVisible()
  await tourCard.getByRole('button', { name: 'Готово' }).click()
  await expect.poll(() => tourState(page)).toMatchObject({ stepId: 'result', status: 'completed' })
  await expect(tourCard).toHaveCount(0)
})
